### ISSUE TITLE
Hostnames not being extracted - xlsx

### ISSUE THREAD

**Issue by shall1569** [cr0hn/openvas_to_report#13]
Tried to go through some of the python code and figure out how the "Hostname" field was being populated.. but alas I am no expert

When exporting to xlsx, there is a Host name field on the vulnerability tabs. 
This is just marked as "-" 
I am using https://github.com/TheGroundZero/openvasreporting/tree/master/openvasreporting, but when raising an issue, it directs me to this GitHub. 

Ask questions, and I will try and explain more if needed

**Comment by cr0hn** [comment]
I just check the "openvasreporting". The owner was forked this project and created his own. You should open an issue or mail the author repo, sorry.
